# =========================
# kitty: clean + catppuccin + good on 16" 2560x1600
# =========================

include fonts/firacode-font.conf
include current-theme.conf
include basic.conf
include vi-mode.conf


